Makefile

I catch build error with missing math.h functions. (Ubuntu 15.04)
For fixing that i've move -lm flag to the end of gcc args.
Mark, my change seems ugly, =\ but i not found more beautiful solution.

Fix building, move -lm flag

---

filerec.c
filerec.h
results-tree.c
results-tree.h
run_dedupe.c

Most of deduped extents can be skip by comparing the physical offset of them.
Before processing a dupe_extents list, we compare all entries and remove the same one.
The patch trades the ioctl cost for a small userspace processing cost.

Don't dedup already deduped extents

---

file_scan.c

Fix segfault introduced by the check, see e56ba0dcff3a9273607de43de83d2e710d7cf7e6
Signed-off-by: Jack Kenrick <github@jack.fr.eu.org>

Skip files that are smaller than bsize

---

duperemove.c

changed
```
[...]
Where "OBJECTS" is a list of files (or directories) which
we want to find duplicate extents in. If a directory is 
specified, all regular files inside of it will be scanned.
[...]
--hashfile		Use a file instead of memory for storing hashes.
[...]
```
to 
```
[...]
"OBJECTS" is a list of files (or directories) which we
want to find duplicate extents in. If a directory is 
specified, all regular files inside of it will be scanned.
[...]
--hashfile=FILE	Use a file instead of memory for storing hashes.
[...]
```

minor reformatting to --help output.

---

util.c
util.h

This PR fixes some problems during compilation on musl libc.

Fix includes for musl, deactivate backtrace on non-glibc targets.

---

dbfile.c
dbfile.h
duperemove.c
file_scan.c
file_scan.h

Hello Mark,
The major stuff in these commits are:
- remove a unused index. Really reduce the db size (30% reduction, according to some tests)
- create index after all the data is inserted: this lower both cpu & memory consumption
- use in-memory database, so a single code path can be used. Plus, according to tests, it reduces by 70% the memory consumptions (really, from 1.6GB to 500MB!)

Improve scanning phase

---

btrfs-extent-same.c

This allows `btrfs-extent-same` to work without root (at least on my 4.4.1 kernel).

btrfs-extent-same: Fix file mode of deduplicated extents

---

hashstats.c

This fixes a -flto warning on gcc 6.1.1.
Warning was:
file_scan.h:28:5: warning: type of ‘add_file_db’ does not match original declaration [-Wlto-type-mismatch]
int add_file_db(const char *filename, uint64_t inum, uint64_t subvolid,
^
hashstats.c:53:5: note: type mismatch in parameter 6
int add_file_db(const char *filename, uint64_t inum, uint64_t subvolid,
^
hashstats.c:53:5: note: ‘add_file_db’ was previously declared here

add_file_db(): make arguments in file_scan.h and hashstats.c match.

---

dedupe.c
duperemove.c
filerec.c
hashstats.c
run_dedupe.c

````
[dedupe.c:108]: (warning) %llu in format string (no. 3) requires 'unsigned long long' but the argument type is 'signed long long'.
[duperemove.c:394]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[duperemove.c:394]: (warning) %u in format string (no. 2) requires 'unsigned int' but the argument type is 'signed int'.
[filerec.c:679]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[filerec.c:687]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[hashstats.c:255]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'int'.
[hashstats.c:255]: (warning) %u in format string (no. 2) requires 'unsigned int' but …
```

fix some format string arguments pointed out by cppcheck:

---

dbfile.c

glibc-2.24 does not include sysmacros.h from types.h, so include it manually.

Fix for: dbfile.c:(.text+0x1330): undefined reference to `makedev'

---

Makefile
file_scan.c
run_dedupe.c

It was reported that it fails to compile for mips and mipsel architectures due to missing __sync* functions. Consider using __atomic instead
see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851261

Use atomic instead of sync

---

file_scan.c
filerec.c

This ensures that we can't end up recursing on encounter with directory symlinks, and that we don't try to dedup content of a symlink as if it were the file it points to.

Never follow symlinks with stat()-style calls. (#202)

---

duperemove.8
duperemove.c
file_scan.c
file_scan.h

It's possible I have a really strange setup. That said, I have a file server based on btrfs and create snapshots on an hourly basis. The snapshots are mounted read-only in a folder and provided via samba for easy recovery by clients.
When deduplicating, the content of the snapshots need not be considered, because the entire content of the snapshots is completely deduplicated already. Furthermore, with 20 snapshots of 300k+ files, the deduplication process becomes an unnecessarily difficult and time-consuming chore.
So, I added the ability to exclude certain files and folders from the deduplication process with a --exclude command-line option. So then I can do
duperemove -drh --exclude=.snapshots --hashfile=dupes.db /path/to/shares
And then only the files I expect to be changing are …

Add --exclude option

---

.gitignore
filerec.c

This should fix #211 .
I am not familiar with kernel stuff. I referred to https://github.com/ColinIanKing/fiemap and thought that previous code reads the address of the next part fiemap from the wrong place.
I also update the `.gitignore` to include more compiled binaries.

Fix out-of-bounds access to fm_extents when reading next part of fiemap

---

Makefile

__atomic* functions are built-in in gcc so there shouldn't be a need to
link against libatomic explicitly.

Don't link with libatomic

---

dbfile.c

For some reason this function was returning EINVAL in case of success.
Instead return 0.

Fix remove_file_hashes_prep retval in case of success

---

xxh3.h

Current xxhash distribution uses xxh3.h header. Duperemove currently
doesn't use this version of xxhash but this is still needed for proper
compilation.

Add missing xxh3.h header

---

file_scan.c

I came across the same issue as in #241 -- turns out `total_bytes_read` (unsigned int) was written into `ret` (int) and overflowed on large files. It would seem in the two places that call `csum_extent`, they only care if value is negative (error), zero (EOF), or positive (continue) and not "how positive" it is -- so I've just added a simple check to fix the return code and send back a 1 instead of `total_bytes_read`.

Handle overflow in csum_extent

---

dbfile.c

Currently if we have 2 extents which have the same hash but different
size it will trigger an abort in dedupe_extent_list. The reason is that
the query used to get dupe extents in dbfile_load_extent_hashes ignores
the len of the extent and instead only matches on digest. This would
result in creating 2 distinct struct dupe_extents with only a single
entry, this in turn results in triggering an assertion in
dedupe_extent_list.
Fix this by changing to the SQL statement responsible for loading dupes
to consider the 'len' column as well.

Handle colliding extents

---

Makefile

GCC has the _headers_ for __atomic built-in, but it still needs library
support on many architectures.  On Debian, this broke armel mipsel m68k
powerpc sh4.
--as-needed does precisely what we want: links the library only if it's
actually required, with no bloat added when not.
This reverts commit 06160235310a98f41c3f0e46e8f42e57dba11bc3.

Revert "Don't link with libatomic"

---

dbfile.c

The argument was made that since the hashfile contains paths and
content hashesh for files and directories that are otherwise protected
by the filesystem permissions. Fix this by explicitly setting the
permissions for a newly created database file to 600.
close #262

Create hash database file with 600 permission

---

duperemove.c
util.c
util.h

On 32-CPU machine with SSD I occasionally get -EMFILE errors when deduping as:
My guess is that we exhausl relatively small 1K default RLIMIT_NOFILE.
The change cranks up the limit from 1K to 512K on x86_64 linux.

duperemove: increase open file limit from default to maximum available

---

Makefile

0ed39333d222c3b171dbdf1ca476ad65ca201d65 broke building from release tarballs. This fixes it as long as you pass VERSION and IS_RELEASE yourself.

Use ?= to set VERSION and IS_RELEASE

---

file_scan.c

The setup: create 100K files 1024 bytes each. This is 100MB input:
echo "Creating directory structure, will take a minute"
mkdir dd
for d in `seq 1 100`; do
mkdir dd/$d
for f in `seq 1 1000`; do
printf "%*s" 1024 "$f" > dd/$d/$f
done
done
sync
Before the change this input took 40 seconds to process:
$ time ./duperemove -q -rd dd/
...
real    0m39,835s
user    1m54,903s
sys     0m8,922s
After the change we get 2x speedup in performance:
$ time ./duperemove -q -rd dd/
...
real    0m14,616s
user    0m11,942s
sys     0m2,580s
The main overhead was in a single `calloc(8MB)` call against each small file. The change should decrease this setup overhead when running against small files.

file_scan.c: don't use calloc() in csum_whole_file()

---

dbfile.c

The idea of the change is to substitute linear scan of `extents` table for lookup in it in block dedupe phase.
Here are the query explanations by `sqlite`:
$ sqlite3 /tmp/foo.db
sqlite> .eqp on
Before the change:
sqlite> SELECT extents.loff, len, poff, flags
FROM extents JOIN (
SELECT digest
FROM extents
GROUP BY digest
HAVING count(*) = 1) AS nondupe_extents
on extents.digest =  nondupe_extents.digest
where extents.ino = ?1 and extents.subvol = ?2;
QUERY PLAN
|--CO-ROUTINE nondupe_extents
|  `--SCAN extents USING COVERING INDEX idx_extent_digest
|--SEARCH extents USING INDEX idx_extents_inosub (ino=? AND subvol=?)
|--BLOOM FILTER ON nondupe_extents (digest=?)
`--SEARCH nondupe_extents USING AUTOMATIC COVERING INDEX (digest=?)
Note the `SCAN extents` part that does full database scan. …

`--dedupe-options=partial`: avoid quadratic slowdown on extent count

---

filerec.c

Before the change `filerec_count_shared()` incorrectly accounted for extent end compared to file end:
$ ls -lh /nix/var/nix/db/db.sqlite
-rw-r--r-- 1 root root 1.4G Nov  9 22:21 /nix/var/nix/db/db.sqlite
Before the change due to incorrect tail handling sharing reported size larger than the file itself:
$ ./show-shared-extents /nix/var/nix/db/db.sqlite
/nix/var/nix/db/db.sqlite: 27065321263104 shared bytes
After the change sharing reports a reasonable value:
$ ./show-shared-extents /nix/var/nix/db/db.sqlite
/nix/var/nix/db/db.sqlite: 1169276928 shared bytes
Note: before the change sharing reported a few orders of magnitude savings larger than initial file size. After the change the value is more reasonable.

filerec_count_shared(): fix sharing accounting

---

file_scan.c

`dbfile_close_handle` takes `struct dbhandle*`; CFI doesn't like it being called as a function taking `void*`. This can be worked around by passing `-fsanitize-cfi-icall-generalize-pointers`, but it seemed easy enough to just make the code compliant.

file_scan: satisfy clang CFI

---

util.c

Without the change `gcc-14` fails the build with `-Werror=format-security` as:
util.c:340:25: error: format not a string literal and no format arguments [-Werror=format-security]
340 |         fprintf(stream, buf);
|                         ^~~
It's a harmless warning as `UUID` has a well-defined set of characters. But `fputs()` expresses intent more directly to print the string as is.

util.c: make debug helper `-Wformat-security`-clean

---

Makefile
completion/zsh/_duperemove

This PR adds zsh compltion for the main duperemove command. I did not create zsh completion for the other commands as after reading the man pages they appeared to be more of debugging commands and not worth the effort.
Unfortunately I don't have the skill to write an equivalent bash completion file.

Add zsh completion for main duperemove command.

---

dbfile.c
dbfile.h
hashstats.c

Avoid temporary tables due to missing indexes.
Added missing indexes.
Made index names consistent.
Removed unused blocks column.
Fixes #347
Tested with (btrfs/compression):
```
data: 584G
hashfile: 2,7G
num_files: 4825823	num_block_hashes: 5293475	num_extent_hashes: 2671643
```

Fix partial deduplication

---

btrfs-extent-same.8

`ioctl_fideduprange` doesn't look like a real manpage.

btrfs-extent-same.8: Fix manpage reference

---

run_dedupe.c

De-duping my Unity Avatar's library on bcachefs always resulted in aborts of this type:
```
❯ gdb --args duperemove -dr --io-threads=1 --hashfile=".duperemove.hash" *
Gathering file list...
[New Thread 0x7ffff41ff6c0 (LWP 221298)]
process_extents: unable to get extent
file /mnt/bcachefs/windowsvm-share/3DModels/WickerBapper-v2.2/Library/ArtifactDB-lock changed
process_extents: unable to get extent
file /mnt/bcachefs/windowsvm-share/3DModels/WickerBapper-v2.2/Library/SourceAssetDB-lock changed
process_extents: unable to get extent
file /mnt/bcachefs/windowsvm-share/3DModels/WickerBapper-v2.2/Library/SourceAssetDB changed
process_extents: unable to get extent
file /mnt/bcachefs/windowsvm-share/3DModels/WickerBapper-v2.2/Library/ArtifactDB changed
Files scanned: 4/4 (100.00%)
Bytes scanned: …
```

dedupe: Skip extents with insufficient duplicates

---

dbfile.c
progress.c
results-tree.h

This fixes builds with clang as well as some instances of undefined behavior.

Fixes found when packaging for Chimera Linux
